// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import path from "node:path";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: `npx tsx ${path.join("prisma", "seed.ts")}`,
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
